apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app2
spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: docker.io/achalpadol/nginx-go-frontend:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          env:
            - name: FRONTEND_SECRET
              valueFrom:
                secretKeyRef:
                  name: frontend-secret
                  key: frontend-secret
